### ISSUE TITLE
gulp-watch & gulp-nodemon

### ISSUE THREAD

**Issue by georgschlenkhoff** [JacksonGariety/gulp-nodemon#77] opened 2015-07-03 14:34 UTC
I'm using `gulp-watch` package that starts also gulp-nodemon, like so:

```
gulp.task('gulp-nodemon', function() {
  nodemon({
    script: 'test/fixtures',
    watch: 'test/fixtures',
    ext: 'js json'
  });
});

gulp.task('watch', ['gulp-nodemon'], function() {
  gulp.start('browser-sync');
  watch('app/**/*', function() {
    browserSync.reload();
  });
```

However, when I quit the gulp watch command with Ctrl + c, then nodemon process is still running. Is there a way how to cleanly exit the process?

**Comment by scottseeker** [comment] 2015-08-28 19:50
I have the same issue.

**Comment by eliot-akira** [comment] 2015-10-06 09:14
Same here. After quitting gulp with Ctrl + c, the process continues to run - and when I enter any key on the bash command line, the process finally ends with an error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: read EIO
  at exports._errnoException (util.js:837:11)
  at TTY.onread (net.js:544:26)
```

I've tried different methods to prevent this, but so far no success. The only workable way I found was to run nodemon and gulp separately.

**Comment by mshwery** [comment] 2015-11-09 16:57
same

**Comment by eliot-akira** [comment] 2015-11-09 22:52
For me, the following finally solved this issue:

```
var monitor = nodemon(options);

process.once('SIGINT', function() {
  monitor.once('exit', function() {
    process.exit();
  });
});
```

I have several watch tasks including nodemon and browser-sync, so your mileage may vary.

**Comment by mshwery** [comment] 2015-11-10 01:07
@eliot-akira what is `process` for you in this closure?

**Comment by theverything** [comment] 2015-11-25 00:48
Thank you for this thread I've been having this issue for the last couple weeks and couldn't figure out why.

I used a modified version of @eliot-akira fix. Which seems to have removed the error.

```
gulp.task('server', function () {
  nodemon({
    script: './server.js',
  })
  .once('exit', function () {
    console.log('Exiting the process');
    process.exit();
  });
});
```

**Comment by PeterPanen** [comment] 2015-12-02 15:16
@theverything 
It seems here that the nodemon exit event also gets triggered when nodemon restarts, due to file changes.

**Comment by glortho** [comment] 2015-12-22 16:40
@eliot-akira thank you!

**Comment by bavellone** [comment] 2015-12-31 22:58
@theverything Just what I was looking for. Thanks!

**Comment by JacksonGariety** [comment] 2016-01-10 21:13
I think this is a duplicate of #33.

**Closed** 2016-01-10 21:17 UTC

**Comment by jwickens** [comment] 2017-02-06 17:19
The following works pretty well for me:
```js
    nodemon.on('start', () => {
        debug('nodemon has started app');
    }).on('quit', () => {
        debug('nodedmon has quit');
        process.exit();
    }).on('restart', function(files) {
        debug('App restarted due to: ', files);
    });
```
