### ISSUE TITLE
Nodemon won't restart on changes

### ISSUE THREAD

**Issue by dwest-ee** [JacksonGariety/gulp-nodemon#68] opened 2015-04-12 09:57 UTC
Hi,

I am using gulp-nodemon 2.0.2 with Node 0.12.2, and Nodemon isn't restarting on changes. My setup looks like:

// gulp start
nodemon({
    script: 'index.js'
  })

// nodemon,json
{
  "verbose": true,
  "watch": ["src/"]
}

**Comment by JacksonGariety** [comment] 2015-04-15 02:13
@dwest-ee does using `nodemon(require('nodemon.json'))` fix it?

**Comment by MikeBarnhardt** [comment] 2015-04-23 15:17
I have the same issue. My task is
```js
gulp.task('default', function () {
    nodemon()
        .on('start', ['watch'])
        .on('change', ['watch']);
});
```
and `nodemon.json` file is
```json
{
    "env": {
        "DEBUG": "citizen:*",
        "NODE_ENV": "development",
        "PORT": 8000
    },
    "ext": "js jsx handlebars",
    "ignore": [
        ".git/",
        "node_modules/"
    ],
    "restartable": "rs",
    "verbose": false,
    "watch": [
        "server/",
        "shared/",
        "test/"
    ]
}
```

I have tried using `nodemon(require('./nodemon.json'))` and it still doesn't work. Removing the `start` and `change` events makes it work, but won't fire my watch task.

The issues I have been running into is that using the `tasks` option will cause the restart to be extremely slow. If I do something like `gulp.task('default', ['watch', 'demon'])` then nodemon restarts multiple times or either the watch task runs but nodemon won't restart. They seem to be at conflict with each other.

**Comment by MikeBarnhardt** [comment] 2015-04-28 12:52
I seem to have figured out a work-around:

```js
var watching = false;

gulp.task('default', function () {
    nodemon()
        .on('start', function () {
            console.info('Demon started');
                        
            if (!watching) {
                gulp.watch(assets.watch.js, ['js']);
                gulp.watch(assets.watch.scss, ['css']);
                watching = true;
            }
        })
        .on('restart', function () {
            console.clear();
        });
});
```

It will now restart nodemon based on the `nodemon.json` watch array and also gulp will run the appropriate tasks `[js]` or `[css]` if those files are saved.

The `watching` variable is to prevent multiple event bindings watching the same files.

Also, I'm using [better-console](https://github.com/mohsen1/better-console) for the improved console functionality.

**Comment by piteer1** [comment] 2015-06-10 12:29
@dwest-ee @JacksonGariety Just an info, I had the same issue when using nodemon and jasmine for tests with jasmine.clock().install() or jasmine.clock().mockDate(). So it's possible this problem is caused by mocking date in tests.

**Comment by nmccready** [comment] 2015-06-25 19:31
This is a bug in nodemon `1.3.7` if you force gulp-nodemon to run `1.3.6` it appears to work. This is running against gulp-nodemon `1.0.5`

**Comment by nmccready** [comment] 2015-06-25 19:36
https://github.com/remy/nodemon/pull/568

**Comment by nmccready** [comment] 2015-06-25 19:37
I confirmed nodemon 1.3.6 fixes gulp-nodemon  2.0.2

**Comment by JacksonGariety** [comment] 2015-08-21 20:56
Fixed in gulp-nodemon 2.0.4 which uses nodemon 1.4.1

**Closed by JacksonGariety** 2015-08-21 20:56 UTC

**Comment by jm-janzen** [comment] 2016-08-08 15:02
Leaving a comment here, because it's a top Google search result for this issue.  My issue was not even related to Gulp, it turned out.

If you're using Vim as your editor, it seems `:w'  does not _always_ trigger a restart.  I had to enter `:e' to rebuffer the file, then subsequent changes were picked up with no problem.

**Comment by JacksonGariety** [comment] 2016-08-08 16:57
@jm-janzen are you running the latest version?

**Comment by jm-janzen** [comment] 2016-08-09 15:01
@JacksonGariety Just checked, and no.  Was in fact running 1.0.5 explicitly!  Since changed that to 2.0.4, and am actively testing that atm.
